### ISSUE TITLE
Wiki Setup Instructions

### ISSUE THREAD

**Issue by ypnos-web** [dereuromark/cakephp-whoops#2]
Thank you for forking the project.

In the Wiki I suggest you add:

> ## Setup for Arch Linux or Antergos
> Install the AUR package `phpstorm-urlhandler`.

Also it might be good to add that for browsers other than Firefox, installing the .desktop file from sanduhrs/phpstorm-url-handler is the way to go to make the URL work on a modern GNU/Linux desktop.

**Comment by dereuromark** [comment]
In the Wiki I only linked to other resources, I do not recall adding arch linux or antergos.
Feel free to add that approach under a separate headline - I didnt get it to work on my Linux Mint + Chrome, so I stuck to the FF handler solution.

**Comment by ypnos-web** [comment]
I wrote this issue because I cannot edit the wiki. Would be happy to save you the hassle and add it myself though if you check access rights.

**Comment by dereuromark** [comment]
Ah, found the setting.
I opened it up, thx
